blank_issues_enabled: false
contact_links:
  - name: Questions and Community Support
    url: https://github.com/tagesspiegel/kubernetes-namespace-permission-manager/discussions
    about: Please ask and answer questions here.
