apiVersion: v1
kind: Namespace
metadata:
  name: with-role-ref
  labels:
    ns.tagesspiegel.de/permission-control: "manage"
  annotations:
    ns.tagesspiegel.de/rolebinding-subjects: kind=ServiceAccount;name=default,kind=User;name=default,kind=Group;name=default
    ns.tagesspiegel.de/rolebinding-roleref: kind=Role;apiGroup=rbac.authorization.k8s.io;name=namespace-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  namespace: with-role-ref
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
