apiVersion: v1
kind: Namespace
metadata:
  name: with-custom-role
  labels:
    ns.tagesspiegel.de/permission-control: "manage"
  annotations:
    ns.tagesspiegel.de/rolebinding-subjects: kind=ServiceAccount;name=default,kind=User;name=default,kind=Group;name=default
    ns.tagesspiegel.de/custom-role-rules: verbs=*;apiGroups=*;resources=*
